export class Doctor{
    _id: string;
    name: String;
    username: String;
    email: String;
    dateofbirth: Date;
    gender: String;
    mobileno: String;
    altermobileno: String;
    country: String;
    state: String;
    address1: String;
    address2: String;
    profileimg: any;
    speciality: String;
    monday : [{
      m1: Boolean,
      m2: Boolean,
      m3: Boolean,
      m4: Boolean,
      m5: Boolean,
      m6: Boolean,
      m7: Boolean,
      m8: Boolean,
      m9: Boolean,
      m10: Boolean,
      m11: Boolean,
      m12: Boolean,
      m13: Boolean,
      m14: Boolean,
      m15: Boolean,
      m16: Boolean,
      m17: Boolean,
      m18: Boolean
       }];
     tuesday: {
      t1: Boolean,
      t2: Boolean,
      t3: Boolean,
      t4: Boolean,
      t5: Boolean,
      t6: Boolean,
      t7: Boolean,
      t8: Boolean,
      t9: Boolean,
      t10: Boolean,
      t11: Boolean,
      t12: Boolean,
      t13: Boolean,
      t14: Boolean,
      t15: Boolean,
      t16: Boolean,
      t17: Boolean,
      t18: Boolean
     };
     wednesday: {
      w1: Boolean,
      w2: Boolean,
      w3: Boolean,
      w4: Boolean,
      w5: Boolean,
      w6: Boolean,
      w7: Boolean,
      w8: Boolean,
      w9: Boolean,
      w10: Boolean,
      w11: Boolean,
      w12: Boolean,
      w13: Boolean,
      w14: Boolean,
      w15: Boolean,
      w16: Boolean,
      w17: Boolean,
      w18: Boolean
     };
     thursday: {
      th1: Boolean,
      th2: Boolean,
      th3: Boolean,
      th4: Boolean,
      th5: Boolean,
      th6: Boolean,
      th7: Boolean,
      th8: Boolean,
      th9: Boolean,
      th10: Boolean,
      th11: Boolean,
      th12: Boolean,
      th13: Boolean,
      th14: Boolean,
      th15: Boolean,
      th16: Boolean,
      th17: Boolean,
      th18: Boolean
     };
     friday: {
      f1: Boolean,
      f2: Boolean,
      f3: Boolean,
      f4: Boolean,
      f5: Boolean,
      f6: Boolean,
      f7: Boolean,
      f8: Boolean,
      f9: Boolean,
      f10: Boolean,
      f11: Boolean,
      f12: Boolean,
      f13: Boolean,
      f14: Boolean,
      f15: Boolean,
      f16: Boolean,
      f17: Boolean,
      f18: Boolean
     };
     saturday: {
      s1: Boolean,
      s2: Boolean,
      s3: Boolean,
      s4: Boolean,
      s5: Boolean,
      s6: Boolean,
      s7: Boolean,
      s8: Boolean,
      s9: Boolean,
      s10: Boolean,
      s11: Boolean,
      s12: Boolean,
      s13: Boolean,
      s14: Boolean,
      s15: Boolean,
      s16: Boolean,
      s17: Boolean,
      s18: Boolean
     };
     sunday: {
      su1: Boolean,
      su2: Boolean,
      su3: Boolean,
      su4: Boolean,
      su5: Boolean,
      su6: Boolean,
      su7: Boolean,
      su8: Boolean,
      su9: Boolean,
      su10: Boolean,
      su11: Boolean,
      su12: Boolean,
      su13: Boolean,
      su14: Boolean,
      su15: Boolean,
      su16: Boolean,
      su17: Boolean,
      su18: Boolean
     };
      }
  